apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: {{ .Release.Name }}-service
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ quote $value }}
  {{- end }}