apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-service
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-service
    spec:
      volumes:
      - name: llm-model
        hostPath:
          path: "/Users/yak/dev/llm/models"
      containers:
      - name: {{ .Release.Name }}-service
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        volumeMounts:
        - name: llm-model
          mountPath: /app/models
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-config