openapi: 3.0.0
info:
  title: LLM Text Generation Service
  version: 1.0.0
  description: API for generating text using a Large Language Model (LLM)
  contact:
    email: ybakhan@gmail.com
    name: Yasser Khan
servers:
  - description: Local
    url: 'http://localhost:8080'

paths:
  /generate:
    post:
      summary: Generate text based on a given prompt
      description: |
        Accepts a prompt in the request payload and returns generated text along with the response time.
      operationId: generateText
      requestBody:
        description: JSON payload containing the prompt for text generation
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                prompt:
                  type: string
                  description: The text prompt to generate text from
              required:
                - prompt
              example:
                prompt: "Once upon a time "
      responses:
        '200':
          description: Successful response with generated text and response time
          content:
            application/json:
              schema:
                type: object
                properties:
                  generated_text:
                    type: string
                    description: The text generated by the LLM based on the prompt
                  response_time:
                    type: number
                    format: float
                    description: The time taken to generate the text in seconds
                example:
                  generated_text: "in a kingdom far away..."
                  response_time: 0.5
        '400':
          description: Bad Request - Missing prompt or invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    description: Description of the error
                example:
                  detail: "No prompt provided in payload"
        '500':
          description: Internal Server Error - An error occurred during text generation
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    description: Description of the error
                example:
                  detail: "Model generation failed: Could not process the prompt"