apiVersion: v1
kind: Service
metadata:
  name: llm-service
spec:
  selector:
    app: llm-service
  ports:
    - protocol: TCP
      port: 80              # internal service port
      targetPort: 8000
      nodePort: 30000  # external service port 
  type: NodePort
  sessionAffinity: None