replicaCount: 1

image:
  repository: qlik-llm-service
  tag: latest
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: "1"
    memory: "512Mi"   # a Fast API worker node can comfortably load a distilGPT2 model
  limits:
    cpu: "1"
    memory: "1024Mi"

config:
  MAX_LENGTH: "32"
  MAX_NEW_TOKENS: "20"
  TEMPERATURE: "0.2"
  TOP_K: "5"
  TOP_P: "0.7"
  REPETITION_PENALTY: "1.1"
  MODEL_DIR_NAME: "distilgpt2"

hpa:
  minReplicas: 3
  maxReplicas: 5
  cpuUtilization: 50

service:
  type: NodePort
  port: 80
  targetPort: 8000
  nodePort: 30000